// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "steuerpilot-go/templates/layout"

func Upload() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"max-w-2xl mx-auto px-4 py-10\"><h1 class=\"text-2xl font-bold mb-2\">Dokumente hochladen</h1><p class=\"text-gray-600 mb-8\">Laden Sie Ihren Lohnausweis hoch. Kontoauszug und Säule 3a sind optional. Claude Vision extrahiert die Daten automatisch.</p><form id=\"upload-form\" hx-post=\"/htmx/extraction/preview\" hx-target=\"#extraction-result\" hx-swap=\"innerHTML\" hx-encoding=\"multipart/form-data\" class=\"space-y-4 bg-white border rounded-lg p-6 shadow-sm\"><div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Dokumenttyp</label> <select name=\"docType\" class=\"w-full border rounded px-3 py-2 text-sm\"><option value=\"lohnausweis\">Lohnausweis</option> <option value=\"kontoauszug\">Kontoauszug</option> <option value=\"3a\">Säule 3a</option></select></div><div><label class=\"block text-sm font-medium text-gray-700 mb-1\">Datei (PDF, JPG, PNG, WebP)</label> <input type=\"file\" name=\"file\" accept=\".pdf,.jpg,.jpeg,.png,.webp\" class=\"w-full text-sm text-gray-600 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-medium file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100\" required></div><button type=\"submit\" class=\"flex items-center gap-2 bg-blue-600 text-white px-6 py-2 rounded font-medium hover:bg-blue-700 transition\"><span class=\"htmx-indicator text-sm\">Wird analysiert…</span> <span>Analysieren</span></button></form><div id=\"extraction-result\" class=\"mt-6\"></div><div class=\"mt-10 border-t pt-6 flex justify-between items-center text-sm\"><a href=\"/\" class=\"text-gray-400 hover:underline\">← Zurück</a> <a href=\"/wizard/personalien\" class=\"text-blue-600 hover:underline\">Weiter ohne Dokument-Upload →</a></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base("Dokumente hochladen").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
