// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package wizard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"steuerpilot-go/internal/models"
	"steuerpilot-go/templates/pages"
)

func Abzuege(sf models.Steuerfall) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form method=\"POST\" action=\"/wizard/abzuege/submit\" class=\"space-y-6\"><fieldset class=\"border rounded-lg p-4\"><legend class=\"text-sm font-semibold px-1 text-gray-700\">Fahrkosten</legend><div class=\"space-y-3 mt-2\"><div><label class=\"block text-sm font-medium mb-1\">Transportmittel</label> <select name=\"fahrkosten_art\" class=\"w-full border rounded px-3 py-2 text-sm\"><option value=\"oev\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Fahrkosten.Art == models.FahrkostenOev {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">Öffentlicher Verkehr</option> <option value=\"auto\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Fahrkosten.Art == models.FahrkostenAuto {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">Auto (km-Pauschale)</option> <option value=\"motorrad\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Fahrkosten.Art == models.FahrkostenMotorrad {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, ">Motorrad</option> <option value=\"velo\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Fahrkosten.Art == models.FahrkostenVelo {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">Velo (Pauschale)</option> <option value=\"keine\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Fahrkosten.Art == models.FahrkostenKeine {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, ">Keine Fahrkosten</option></select></div><div class=\"grid grid-cols-2 gap-3\"><div><label class=\"block text-sm font-medium mb-1\">ÖV-Kosten / Distanz km (CHF)</label> <input type=\"number\" name=\"fahrkosten_betrag\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Berufskosten.Fahrkosten.OevKosten))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 33, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Arbeitstage</label> <input type=\"number\" name=\"fahrkosten_arbeitstage\" min=\"0\" max=\"366\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", sf.Abzuege.Berufskosten.Fahrkosten.Arbeitstage))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 44, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div></div></div></fieldset><fieldset class=\"border rounded-lg p-4\"><legend class=\"text-sm font-semibold px-1 text-gray-700\">Verpflegung</legend><div class=\"space-y-3 mt-2\"><div class=\"flex gap-4\"><label class=\"flex items-center gap-2 text-sm cursor-pointer\"><input type=\"checkbox\" name=\"verpflegung_auswaertig\" value=\"1\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Verpflegung.Auswaertig {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "> Auswärtige Verpflegung</label> <label class=\"flex items-center gap-2 text-sm cursor-pointer\"><input type=\"checkbox\" name=\"verpflegung_kantine\" value=\"1\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sf.Abzuege.Berufskosten.Verpflegung.Kantine {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "> Kantine</label></div><div><label class=\"block text-sm font-medium mb-1\">Arbeitstage</label> <input type=\"number\" name=\"verpflegung_arbeitstage\" min=\"0\" max=\"366\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", sf.Abzuege.Berufskosten.Verpflegung.Arbeitstage))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 81, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div></div></fieldset><fieldset class=\"border rounded-lg p-4\"><legend class=\"text-sm font-semibold px-1 text-gray-700\">Vorsorge &amp; Versicherungen</legend><div class=\"grid grid-cols-2 gap-3 mt-2\"><div><label class=\"block text-sm font-medium mb-1\">Säule 3a (CHF)</label> <input type=\"number\" name=\"saeule3a\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Saeule3a))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 97, Col: 55}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Versicherungsprämien (CHF)</label> <input type=\"number\" name=\"versicherungspraemien\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Versicherungspraemien))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 108, Col: 68}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div></div></fieldset><fieldset class=\"border rounded-lg p-4\"><legend class=\"text-sm font-semibold px-1 text-gray-700\">Weitere Abzüge</legend><div class=\"grid grid-cols-2 gap-3 mt-2\"><div><label class=\"block text-sm font-medium mb-1\">Krankheitskosten (CHF)</label> <input type=\"number\" name=\"krankheitskosten\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Krankheitskosten))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 124, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Schuldzinsen (CHF)</label> <input type=\"number\" name=\"schuldzinsen\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Schuldzinsen))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 135, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Unterhaltsbeiträge (CHF)</label> <input type=\"number\" name=\"unterhaltsbeitraege\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Unterhaltsbeitraege))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 146, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Spenden (CHF)</label> <input type=\"number\" name=\"spenden\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Spenden))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 157, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div><div><label class=\"block text-sm font-medium mb-1\">Weiterbildung (CHF)</label> <input type=\"number\" name=\"weiterbildung\" step=\"0.01\" min=\"0\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", sf.Abzuege.Weiterbildung))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/wizard/abzuege.templ`, Line: 168, Col: 60}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\" class=\"w-full border rounded px-3 py-2 text-sm\"></div></div></fieldset><div class=\"flex justify-between pt-2 border-t\"><a href=\"/wizard/einkommen\" class=\"text-gray-500 hover:underline text-sm\">← Zurück</a> <button type=\"submit\" class=\"bg-blue-600 text-white px-6 py-2 rounded font-medium hover:bg-blue-700 transition\">Weiter →</button></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = pages.WizardLayout("Abzüge", 2).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
